/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example.thrift.config;

import java.util.HashMap;
import java.util.Map;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class ServiceConfigurationConstants {

  public static final int SERVICE_PORT = 9090;

  public static final Map<String,Integer> MAP_CONST = new HashMap<String,Integer>();
  static {
    MAP_CONST.put("hello", 9000);
    MAP_CONST.put("world", 10000);
    MAP_CONST.put("nifty", 11000);
  }

}
